"""
WBench-driven, action-controlled inference for Matrix-Game-3.

This subclasses the standard (non-interactive) ``MatrixGame3Pipeline`` and adds a
``generate_case`` method that:

  * sources the per-clip keyboard/mouse actions from a *given* WBench action list
    (instead of ``utils.utils.get_data`` -> ``Bench_actions_universal`` random
    actions, or the interactive pipeline's ``input()`` prompts),
  * is *re-entrant*: it does NOT call ``exit()`` / ``destroy_process_group()`` so
    the 5B model can be loaded once and reused across many cases, and
  * saves a CLEAN concatenated mp4 (no keyboard/mouse HUD overlay) so the output
    is usable for downstream evaluation later.

Turn -> clip mapping (confirmed): one WBench turn == one MG3 autoregressive clip,
so ``num_iterations = n_turns``. MG3 emits 57 frames for clip 0 and 40 frames for
each later clip, exactly like the interactive pipeline; we build the full-length
per-frame action arrays by concatenating each turn's action (57 then 40 frames),
which matches the windowing the base ``generate`` loop already does.

Nothing in the existing CLI path (``generate.py`` / ``inference_pipeline.py`` /
``inference_interactive_pipeline.py``) is modified.
"""
import math
import os

import numpy as np
import torch
import torch.distributed as dist
from tqdm import tqdm

from wan.utils.fm_solvers_unipc import FlowUniPCMultistepScheduler
from wan.utils.utils import save_video
from utils.cam_utils import (
    compute_relative_poses,
    get_extrinsics,
    get_intrinsics,
    select_memory_idx_fov,
    _interpolate_camera_poses_handedness,
)
from utils.transform import get_video_transform
from utils.utils import (
    build_plucker_from_c2ws,
    build_plucker_from_pose,
    compute_all_poses_from_actions,
)
from pipeline.inference_pipeline import MatrixGame3Pipeline

# MG3 autoregressive clip sizes (must match the base generate loop).
FIRST_CLIP_FRAME = 57
CLIP_FRAME = 56
PAST_FRAME = 16
LATER_CLIP_NEW_FRAMES = 40  # new frames contributed by each clip after the first


def num_frames_for_turns(num_iterations: int) -> int:
    """Total per-frame length for ``num_iterations`` clips (== n_turns)."""
    return FIRST_CLIP_FRAME + (num_iterations - 1) * LATER_CLIP_NEW_FRAMES


def build_action_conditions(actions, num_iterations):
    """Expand per-turn WBench actions into full-length per-frame condition tensors.

    Each ``actions[k]`` is a dict with ``keyboard`` (len-6 one-hot [W,S,A,D,_,_])
    and ``mouse`` (len-2 [pitch, yaw] in {-0.1, 0, +0.1}) -- exactly MG3's
    convention (see WBench ``src/models/action/actions.py``).

    Returns ``(keyboard_all [T, 6], mouse_all [T, 2])`` float tensors where
    ``T == num_frames_for_turns(num_iterations)``. Turn 0 is held for 57 frames,
    every later turn for 40 frames, mirroring the interactive pipeline.
    """
    assert len(actions) >= num_iterations, (
        f"need >= {num_iterations} actions, got {len(actions)}"
    )
    per_turn_frames = [FIRST_CLIP_FRAME] + [LATER_CLIP_NEW_FRAMES] * (num_iterations - 1)

    kb_chunks, ms_chunks = [], []
    for k in range(num_iterations):
        n = per_turn_frames[k]
        kb = torch.tensor(actions[k]["keyboard"], dtype=torch.float32).reshape(1, -1)
        ms = torch.tensor(actions[k]["mouse"], dtype=torch.float32).reshape(1, -1)
        assert kb.shape[1] == 6, f"keyboard must be 6-dim, got {kb.shape[1]}"
        assert ms.shape[1] == 2, f"mouse must be 2-dim, got {ms.shape[1]}"
        kb_chunks.append(kb.repeat(n, 1))
        ms_chunks.append(ms.repeat(n, 1))

    keyboard_all = torch.cat(kb_chunks, dim=0)
    mouse_all = torch.cat(ms_chunks, dim=0)
    return keyboard_all, mouse_all


def get_data_from_actions(num_frames, height, width, pil_image, keyboard_all, mouse_all,
                          device=None, dtype=None):
    """Action-driven analogue of ``utils.utils.get_data``.

    Identical to ``get_data`` except the keyboard/mouse arrays are supplied
    (from a WBench case) rather than generated by ``Bench_actions_universal``.
    Returns ``(current_image, extrinsics_all, keyboard_cond[1,T,6], mouse_cond[1,T,2])``.
    """
    input_image = torch.from_numpy(np.array(pil_image)).unsqueeze(0)
    input_image = input_image.permute(0, 3, 1, 2)

    def normalize_to_neg_one_to_one(x):
        return 2.0 * x - 1.0

    transform = get_video_transform(height, width, normalize_to_neg_one_to_one)
    input_image = transform(input_image)
    input_image = input_image.transpose(0, 1).unsqueeze(0)  # b c t h w

    first_pose = np.concatenate([np.zeros(3), np.zeros(2)], axis=0)
    all_poses = compute_all_poses_from_actions(keyboard_all, mouse_all, first_pose=first_pose)
    positions = all_poses[:, :3].tolist()
    rotations = np.concatenate(
        [np.zeros((all_poses.shape[0], 1)), all_poses[:, 3:5]], axis=1
    ).tolist()
    extrinsics_all = get_extrinsics(rotations, positions)

    return (
        input_image.to(device, dtype),
        extrinsics_all,
        keyboard_all.to(device, dtype).unsqueeze(0),
        mouse_all.to(device, dtype).unsqueeze(0),
    )


class MatrixGame3WBenchPipeline(MatrixGame3Pipeline):
    """MG3 pipeline with a re-entrant, action-fed ``generate_case``.

    ``__init__`` is inherited unchanged from ``MatrixGame3Pipeline`` (model load,
    int8, FSDP/SP, VAE). Use serial VAE (do not pass ``use_async_vae``) for batch.
    """

    @torch.no_grad()
    def generate_case(
        self,
        text,
        pil_image,
        actions,
        save_path,
        size="704*1280",
        num_inference_steps=3,
        shift=5.0,
        guide_scale=5.0,
        seed=42,
        use_base_model=False,
        fps=16,
        args=None,
    ):
        """Render one WBench case as a single clean autoregressive rollout.

        Args:
            text: static prompt for the whole clip.
            pil_image: PIL.Image first frame (I2V conditioning).
            actions: list of per-turn dicts with ``keyboard`` (6) and ``mouse`` (2).
            save_path: output mp4 path (written on rank 0 only).
            size: "H*W" string (e.g. "704*1280").
            fps: playback fps for the saved video.
        Returns:
            ``save_path`` on rank 0, else ``None``.
        """
        weight_dtype = torch.bfloat16
        height = int(size.split("*")[0])
        width = int(size.split("*")[1])
        max_area = height * width

        num_iterations = len(actions)
        assert num_iterations >= 1, "a case must have at least one turn"
        num_frames = num_frames_for_turns(num_iterations)

        generator = torch.Generator(device=self.device).manual_seed(int(seed))

        keyboard_all, mouse_all = build_action_conditions(actions, num_iterations)
        current_image, extrinsics_all, keyboard_condition_all, mouse_condition_all = \
            get_data_from_actions(
                num_frames, height, width, pil_image, keyboard_all, mouse_all,
                device=self.device, dtype=weight_dtype,
            )

        cond = self.text_encoder([text], device=self.device)
        neg_cond = self.text_encoder([self.config.sample_neg_prompt], device=self.device)

        h_orig = current_image.shape[-2]
        w_orig = current_image.shape[-1]
        aspect_ratio = h_orig / w_orig
        lat_h = round(
            np.sqrt(max_area * aspect_ratio) // self.vae_stride[1]
            // self.patch_size[1] * self.patch_size[1]
        )
        lat_w = round(
            np.sqrt(max_area / aspect_ratio) // self.vae_stride[2]
            // self.patch_size[2] * self.patch_size[2]
        )
        target_h = lat_h * self.vae_stride[1]
        target_w = lat_w * self.vae_stride[2]

        base_K = get_intrinsics(target_h, target_w)

        if self.rank == 0:
            img_cond = self.vae.encode([current_image[0]])[0].unsqueeze(0).to(
                device=self.device, dtype=weight_dtype).contiguous()
        else:
            img_cond = torch.zeros(
                (1, 48, 1, lat_h, lat_w), device=self.device, dtype=weight_dtype
            ).contiguous()
        if dist.is_initialized():
            dist.broadcast(img_cond, src=0)

        max_lat_f = (FIRST_CLIP_FRAME - 1) // self.vae_stride[0] + 1
        max_mem_f = 5
        max_total_f = max_lat_f + max_mem_f
        max_seq_len = max_total_f * lat_h * lat_w // (self.patch_size[1] * self.patch_size[2])
        if self.sp_size > 1:
            max_seq_len = int(math.ceil(max_seq_len / self.sp_size)) * self.sp_size

        # Local clip geometry (mirrors base generate()).
        first_clip_frame = FIRST_CLIP_FRAME
        clip_frame = CLIP_FRAME
        past_frame = PAST_FRAME

        vae_cache = [None for _ in range(34)]
        total_frames = 0
        all_latents_list = []
        all_videos_list = []

        for clip_idx in range(num_iterations):
            first_clip = (clip_idx == 0)
            if self.rank == 0:
                print(f" Iteration {clip_idx + 1}/{num_iterations}", flush=True)

            def align_frame_to_block(frame_idx):
                return (frame_idx - 1) // 4 * 4 + 1 if frame_idx > 0 else 1

            def get_latent_idx(frame_idx):
                return (frame_idx - 1) // 4 + 1

            current_end_frame_idx = first_clip_frame if first_clip \
                else first_clip_frame + clip_idx * (clip_frame - past_frame)
            current_start_frame_idx = 0 if first_clip else current_end_frame_idx - clip_frame

            c2ws_chunk = extrinsics_all[current_start_frame_idx:current_end_frame_idx]
            src_indices = np.linspace(
                current_start_frame_idx, current_end_frame_idx - 1,
                first_clip_frame if first_clip else clip_frame)
            tgt_len = (first_clip_frame - 1) // 4 + 1 if first_clip else (clip_frame // 4)
            tgt_indices = np.linspace(
                0 if first_clip else current_start_frame_idx + 3,
                current_end_frame_idx - 1, tgt_len)
            c2ws_chunk_gpu = c2ws_chunk.to(device=self.device)

            plucker = build_plucker_from_c2ws(
                c2ws_chunk_gpu, src_indices, tgt_indices, framewise=True,
                base_K=base_K, target_h=target_h, target_w=target_w,
                lat_h=lat_h, lat_w=lat_w)
            plucker_no_mem = plucker

            if first_clip:
                x_memory = None
                memory_mouse_condition = None
                memory_keyboard_condition = None
                latent_idx = None
                timestep_memory = None
            else:
                if self.rank == 0:
                    selected_index_base = [current_end_frame_idx - o for o in range(1, 34, 8)]
                    selected_index = select_memory_idx_fov(
                        extrinsics_all, current_start_frame_idx, selected_index_base,
                        use_gpu=True)
                    selected_index[-1] = 4
                    selected_index_base = [current_end_frame_idx - o for o in range(1, 34, 8)]
                else:
                    selected_index = [0] * 5
                    selected_index_base = [current_end_frame_idx - o for o in range(1, 34, 8)]

                if dist.is_initialized():
                    dist.broadcast_object_list(selected_index, src=0)

                memory_pluckers = []
                latent_idx = []
                for mem_idx, reference_idx in zip(selected_index, selected_index_base):
                    l_idx = get_latent_idx(mem_idx)
                    latent_idx.append(l_idx)

                    mem_idx_aligned = align_frame_to_block(mem_idx)
                    mem_block = extrinsics_all[mem_idx_aligned:mem_idx_aligned + 4]
                    mem_src = np.linspace(mem_idx_aligned, mem_idx_aligned + 3, mem_block.shape[0])
                    mem_tgt = np.array([mem_idx_aligned + 3], dtype=np.float32)
                    mem_pose = _interpolate_camera_poses_handedness(
                        src_indices=mem_src,
                        src_rot_mat=mem_block[:, :3, :3].cpu().numpy(),
                        src_trans_vec=mem_block[:, :3, 3].cpu().numpy(),
                        tgt_indices=mem_tgt,
                    )
                    reference_pose = extrinsics_all[reference_idx:reference_idx + 1]
                    rel_pair = torch.cat([reference_pose, mem_pose], dim=0)
                    rel_pose = compute_relative_poses(rel_pair, framewise=False)[1:2]
                    rel_pose_gpu = rel_pose.to(device=self.device)
                    memory_pluckers.append(
                        build_plucker_from_pose(
                            rel_pose_gpu, base_K=base_K, target_h=target_h,
                            target_w=target_w, lat_h=lat_h, lat_w=lat_w))

                plucker = torch.cat(memory_pluckers + [plucker], dim=2)
                src = torch.cat(all_latents_list, dim=2)
                x_memory = src[:, :, latent_idx]
                memory_mouse_condition = torch.ones((1, len(selected_index), 2)).to(
                    device=self.device, dtype=weight_dtype)
                memory_keyboard_condition = -torch.ones((1, len(selected_index), 6)).to(
                    device=self.device, dtype=weight_dtype)
                timestep_memory = x_memory.new_zeros(
                    (1, x_memory.shape[2] * x_memory.shape[3] * x_memory.shape[4] // 4))

            keyboard_condition = keyboard_condition_all[:, current_start_frame_idx:current_end_frame_idx]
            mouse_condition = mouse_condition_all[:, current_start_frame_idx:current_end_frame_idx]
            plucker = plucker.to(device=self.device, dtype=weight_dtype)
            plucker_no_mem = plucker_no_mem.to(device=self.device, dtype=weight_dtype)

            test_scheduler = FlowUniPCMultistepScheduler()
            test_scheduler.set_timesteps(num_inference_steps, device=self.device, shift=shift)
            timesteps = test_scheduler.timesteps

            latent_start_idx = get_latent_idx(current_start_frame_idx)
            latent_end_idx = get_latent_idx(current_end_frame_idx)

            latents = torch.randn(
                (1, 48, latent_end_idx - latent_start_idx, img_cond.shape[-2], img_cond.shape[-1]),
                generator=generator, device=self.device, dtype=weight_dtype)
            latents = torch.cat([img_cond, latents[:, :, img_cond.shape[2]:]], dim=2)

            conditions_full = {
                "mouse_cond": mouse_condition,
                "keyboard_cond": keyboard_condition,
                "context": cond,
                "plucker_emb": plucker,
                "x_memory": x_memory,
                "timestep_memory": timestep_memory,
                "keyboard_cond_memory": memory_keyboard_condition,
                "mouse_cond_memory": memory_mouse_condition,
                "memory_latent_idx": latent_idx,
                "predict_latent_idx": (latent_start_idx, latent_end_idx),
                "fa_version": self.fa_version,
            }
            conditions_null = {
                "mouse_cond": torch.ones_like(mouse_condition).to(device=self.device, dtype=weight_dtype),
                "keyboard_cond": -torch.ones_like(keyboard_condition).to(device=self.device, dtype=weight_dtype),
                "context": neg_cond,
                "plucker_emb": plucker_no_mem,
                "x_memory": None,
                "timestep_memory": None,
                "keyboard_cond_memory": None,
                "mouse_cond_memory": None,
                "memory_latent_idx": None,
                "predict_latent_idx": (latent_start_idx, latent_end_idx),
            }

            for _, t in enumerate(tqdm(timesteps, disable=(self.rank != 0))):
                latent_model_input = latents
                timestep = latents.new_full(
                    (latents.shape[2], latents.shape[3] * latents.shape[4] // 4), t)
                timestep[:img_cond.shape[2]].zero_()
                timestep = timestep.flatten().unsqueeze(0)

                model_kwargs = {"x": latent_model_input, "t": timestep,
                                "seq_len": max_seq_len, **conditions_full}
                model_kwargs_null = {"x": latent_model_input, "t": timestep,
                                     "seq_len": max_seq_len, **conditions_null}

                if use_base_model:
                    noise_pred_full = self.model(**model_kwargs)
                    noise_pred_null = self.model(**model_kwargs_null)
                    noise_pred = noise_pred_null + guide_scale * (noise_pred_full - noise_pred_null)
                else:
                    noise_pred = self.model(**model_kwargs)

                latents = test_scheduler.step(noise_pred, t, latents, return_dict=False)[0]
                latents = torch.cat([img_cond, latents[:, :, img_cond.shape[2]:]], dim=2)

            img_cond = latents[:, :, -4:]
            denoised_pred = latents if first_clip else latents[:, :, -10:]

            # Serial VAE decode (rank 0). No HUD overlay -> clean frames.
            if self.rank == 0:
                vae_profiler = {}
                do_compile = getattr(args, "compile_vae", False) and clip_idx >= 1
                vae_segment_size = int(os.environ.get("WAN_VAE_SEGMENT_SIZE", "4"))
                video, vae_cache = self.vae.stream_decode(
                    denoised_pred.to(dtype=self.vae.dtype),
                    vae_cache,
                    first_chunk=first_clip,
                    segment_size=vae_segment_size,
                    profiler=vae_profiler,
                    compile_decoder=do_compile,
                )
                all_videos_list.append(video.cpu())

            all_latents_list.append(denoised_pred)
            total_frames += FIRST_CLIP_FRAME if first_clip else LATER_CLIP_NEW_FRAMES

        out = None
        if self.rank == 0 and len(all_videos_list) > 0:
            concatenated = torch.concat(all_videos_list, dim=2)  # [1, C, T, H, W] in [-1, 1]
            os.makedirs(os.path.dirname(os.path.abspath(save_path)), exist_ok=True)
            save_video(
                tensor=concatenated,
                save_file=save_path,
                fps=fps,
                nrow=1,
                normalize=True,
                value_range=(-1, 1),
            )
            out = save_path

        if dist.is_initialized():
            dist.barrier()
        return out
